SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Indexes */

DROP INDEX COUNTRY_ID_IDX ON AP;
DROP INDEX VENDOR_ID_IDX ON AP;
DROP INDEX AP_TYPE_ID_IDX ON AP;
DROP INDEX RADIO_ID_IDX ON NETWORK;
DROP INDEX ENCRYPTION_ID_IDX ON NETWORK;
DROP INDEX AP_ID_IDX ON RADIO;



/* Drop Tables */

DROP TABLE NETWORK;
DROP TABLE RADIO;
DROP TABLE AP;
DROP TABLE AP_CLIENT;
DROP TABLE AP_MODIFY;
DROP TABLE AP_TYPE;
DROP TABLE ENCRYPTION;
DROP TABLE HOST_EXT;
DROP TABLE MAC_VENDOR;
DROP TABLE VENDOR;




/* Create Tables */

CREATE TABLE AP
(
	-- 自增长ID
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
	MAC_ADDRESS VARCHAR(20) NOT NULL,
	-- 自增长ID
	AP_TYPE_ID BIGINT COMMENT '自增长ID',
	-- 自增长主键
	VENDOR_ID BIGINT COMMENT '自增长主键',
	PRIMARY KEY (ID)
);


CREATE TABLE AP_CLIENT
(
	-- 自增长ID
	ID BIGINT NOT NULL COMMENT '自增长ID',
	MAC_ADDRESS VARCHAR(20),
	-- 厂商ID
	VENDOR_ID VARCHAR(255) COMMENT '厂商ID',
	PRIMARY KEY (ID)
);


CREATE TABLE AP_MODIFY
(
	-- 自增长ID
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
	-- ap_id
	AP_ID BIGINT NOT NULL COMMENT 'ap_id',
	PRIMARY KEY (ID)
);


CREATE TABLE AP_TYPE
(
	-- 自增长ID
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
	-- 名称
	NAME VARCHAR(255) NOT NULL COMMENT '名称',
	PRIMARY KEY (ID)
);


CREATE TABLE ENCRYPTION
(
	-- 自增长ID
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
	ENCRYPTION VARCHAR(255),
	ENCRYPTION_KEY VARCHAR(255),
	PRIMARY KEY (ID)
);


CREATE TABLE HOST_EXT
(
	-- 自增长主键
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
	-- 网卡地址
	MAC_ADDRESS VARCHAR(30) NOT NULL COMMENT '网卡地址',
	-- host名称
	HOST_NAME VARCHAR(255) NOT NULL COMMENT 'host名称',
	PRIMARY KEY (ID)
);


CREATE TABLE MAC_VENDOR
(
	-- 自增长主键
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
	-- 网卡地址
	MAC_ADDRESS VARCHAR(30) NOT NULL COMMENT '网卡地址',
	-- 厂商ID
	VENDOR_ID VARCHAR(255) NOT NULL COMMENT '厂商ID',
	PRIMARY KEY (ID)
);


CREATE TABLE NETWORK
(
	-- 自增长ID
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
	-- 自增长ID
	RADIO_ID BIGINT COMMENT '自增长ID',
	SSID VARCHAR(45),
	VLAN_ID BIGINT,
	ENABLE TINYINT,
	-- 自增长ID
	ENCRYPTION_ID BIGINT COMMENT '自增长ID',
	PRIMARY KEY (ID)
);


CREATE TABLE RADIO
(
	-- 自增长ID
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
	-- 自增长ID
	AP_ID BIGINT COMMENT '自增长ID',
	ENABLE TINYINT,
	CHANNEL VARCHAR(45),
	PRIMARY KEY (ID)
);


CREATE TABLE VENDOR
(
	-- 自增长主键
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
	-- 名称
	NAME VARCHAR(255) NOT NULL COMMENT '名称',
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE RADIO
	ADD FOREIGN KEY (AP_ID)
	REFERENCES AP (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE AP
	ADD FOREIGN KEY (AP_TYPE_ID)
	REFERENCES AP_TYPE (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE NETWORK
	ADD FOREIGN KEY (ENCRYPTION_ID)
	REFERENCES ENCRYPTION (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE NETWORK
	ADD FOREIGN KEY (RADIO_ID)
	REFERENCES RADIO (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE AP
	ADD FOREIGN KEY (VENDOR_ID)
	REFERENCES VENDOR (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;



/* Create Indexes */

CREATE INDEX COUNTRY_ID_IDX ON AP (COUNTRY_ID ASC);
CREATE INDEX VENDOR_ID_IDX ON AP (VENDOR_ID ASC);
CREATE INDEX AP_TYPE_ID_IDX ON AP (AP_TYPE_ID ASC);
CREATE INDEX RADIO_ID_IDX ON NETWORK (RADIO_ID ASC);
CREATE INDEX ENCRYPTION_ID_IDX ON NETWORK (ENCRYPTION_ID ASC);
CREATE INDEX AP_ID_IDX ON RADIO (AP_ID ASC);



